# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0002_remove_staff_posts'),
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(help_text='Usuario Autor', null=True, on_delete=django.db.models.deletion.CASCADE, to='Staff.Staff'),
        ),
    ]
