# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_post_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(help_text='Usuario Autor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='Staff.Staff'),
        ),
    ]
